### ISSUE TITLE
FS22

### ISSUE THREAD

**Issue by regs1980** [Mmtrx/FS19_SeeBales#1]
will there be that for FS22?

**Comment by Mmtrx** [comment]
Ja - hab ich vor. Kann aber noch ein paar Wochen dauern ..

**Comment by regs1980** [comment]
Hört sich gut an, danke.

**Comment by Mmtrx** [comment]
Hier das FS22 [Beta Release](https://github.com/Mmtrx/FS22_SeeBales/releases/tag/v3.0.0.1-beta)
